// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIIFQujhij0KDq-E_UFX6P4GQakv6fXIo',
    appId: '1:878266022412:web:b43edcb4de5861ad648c29',
    messagingSenderId: '878266022412',
    projectId: 'flutter1-d1351',
    authDomain: 'flutter1-d1351.firebaseapp.com',
    storageBucket: 'flutter1-d1351.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMAQLn_RnM-SX2v7qShHNHZOL01CyyYP4',
    appId: '1:878266022412:android:0d574a830ea877c1648c29',
    messagingSenderId: '878266022412',
    projectId: 'flutter1-d1351',
    storageBucket: 'flutter1-d1351.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhz0N8I6qGlWectagYf-XxnFHo0Sp_DZY',
    appId: '1:878266022412:ios:6a6463a4d05d601a648c29',
    messagingSenderId: '878266022412',
    projectId: 'flutter1-d1351',
    storageBucket: 'flutter1-d1351.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhz0N8I6qGlWectagYf-XxnFHo0Sp_DZY',
    appId: '1:878266022412:ios:6a6463a4d05d601a648c29',
    messagingSenderId: '878266022412',
    projectId: 'flutter1-d1351',
    storageBucket: 'flutter1-d1351.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIIFQujhij0KDq-E_UFX6P4GQakv6fXIo',
    appId: '1:878266022412:web:aa7f9651f72a4bf5648c29',
    messagingSenderId: '878266022412',
    projectId: 'flutter1-d1351',
    authDomain: 'flutter1-d1351.firebaseapp.com',
    storageBucket: 'flutter1-d1351.firebasestorage.app',
  );
}
